# Generated by Django 3.2.25 on 2025-03-24 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmodel',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
